name: Android CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Build and run tests
      run: ./gradlew check cascade-compose:verifyPaparazziDebug cascade-compose:allDevicesDebugAndroidTest
