name: Android CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        arch: x86_64
        profile: pixel_5
        disable-animations: true
        force-avd-creation: false
        ram-size: 4096M
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
        script: ./gradlew connectedCheck --stacktrace

    - name: Build and run tests
      run: ./gradlew check cascade-compose:verifyPaparazziDebug
